export const GET_SUBJECT_LIST = "GET_SUBJECT_LIST";
export const GET_SEC_SUBJECT_LIST = "GET_SEC_SUBJECT_LIST";
export const GET_UPDATE_SUBJECT_LIST = "GET_UPDATE_SUBJECT_LIST";
export const GET_REMOVE_SUBJECT_LIST = "GET_REMOVE_SUBJECT_LIST";
